spring.application.name=demo

# DB ?? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=springdbuser
spring.datasource.password=1234

#mybatis??
mybatis.mapper-locations=classpath:mapper/*.xml

#DTO/VO???
mybatis.type-aliases-package=com.example.demo.domain

#map-underscore-to-camel-case -> user_name => username ?? ?? ??
# DB ?? ?? : ??????? : user_name
# java : ????? : username
mybatis.configuration.map-underscore-to-camel-case=true

